spring:
  rabbitmq:
    host: 8.142.74.249 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: guest # 用户名
    password: guest # 密码
    listener:
      simple:
        prefetch: 1 #每个consumer只预取一个，这样可以实现能者多劳